name: Artemis

on:
    repository_dispatch:
        types: [build-chart-benchmark]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install Tools
      run: |
        apt install curl
        apt install jq
    - name: Payload to Json file
      env: 
        JSON: ${{ github.event.client_payload}}
      run: echo "{ JSON }" | jq . > output.json
    - name: Download previous benchmark data
      uses: actions/cache@v2
      with:
        path: ./cache
        key: cache-benchmark
    - name: Store benchmark result
      uses: rhysd/github-action-benchmark@v1
      with:
        # What benchmark tool the output.txt came from
        tool: 'pytest'
        github-token: ${{ secrets.ARTEMIS_GITHUB_TOKEN }}
        auto-push: true
        gh-pages-branch: 'gh-pages'
        benchmark-data-dir-path: 'dev/bench'
        # Where the output from the benchmark tool is stored
        output-file-path: output.json
        # Workflow will fail when an alert happens
        fail-on-alert: true
        alert-threshold: '150%'
        comment-on-alert: true
