name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Make some space 
      run: rm -rf /usr/share/dotnet
    - name: Update docker
      run: apt update && apt upgrade docker docker-compose
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
          python-version: '3.x'
    - name: Remove some folders
      run: |
        rm -rf navitia-docker-compose
        rm -rf artemis_data
        rm -rf artemis_references
    - name: Pull Navitia-docker-compose
      env:
        ARTEMIS_GITHUB_TOKEN: ${{ secrets.ARTEMIS_GITHUB_TOKEN }}
      run: |
        git clone https://$ARTEMIS_GITHUB_TOKEN@github.com/CanalTP/navitia-docker-compose.git --branch master ./navitia-docker-compose
        git clone https://$ARTEMIS_GITHUB_TOKEN@github.com/CanalTP/artemis_data.git --branch master ./artemis_data
        git clone https://$ARTEMIS_GITHUB_TOKEN@github.com/pbench/artemis_references.git --branch artemis_ng ./artemis_references
    - name: Build docker image
      env:
        ARTEMIS_GITHUB_TOKEN: ${{ secrets.ARTEMIS_GITHUB_TOKEN }}
      run: cd navitia-docker-compose/builder_from_package && ./build.sh -o $ARTEMIS_GITHUB_TOKEN -t local -e push -f AzHicham -b dev
    - name: Pull remaining images
      run: make pull_available TAG=local
    - name: Start all dockers 
      run: make start TAG=local
    - name: Run Artemis Test
      run: make test
