name: CI

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: 'recursive'
    - uses: actions/setup-python@v2
      with:
          python-version: '3.x'
    - name: Pull data
      run: rm -rf navitia-docker-compose &
    - name: Pull Navitia-docker-compose
      env:
        ARTEMIS_GITHUB_TOKEN: ${{ secrets.ARTEMIS_GITHUB_TOKEN }}
      run: git clone https://$ARTEMIS_GITHUB_TOKEN@github.com/CanalTP/navitia-docker-compose.git --branch master ./navitia-docker-compose
    - name: Build docker image
      env:
        ARTEMIS_GITHUB_TOKEN: ${{ secrets.ARTEMIS_GITHUB_TOKEN }}
      run: cd navitia-docker-compose/builder_from_package && ./build.sh -o $ARTEMIS_GITHUB_TOKEN -t local -e push -f AzHicham -b dev
    - name: Install docker-compose
      run: apt update && apt install -y docker docker-compose
    - name: Pull remaining images
      run: make pull_available TAG=local
    - name: Start all dockers 
      run: make start TAG=local
    - name: Run Artemis Test
      run: make test