name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Check Docker Version
      run: docker --version
    - name: Install Latest Docker
      run: |
        sudo apt update
        sudo apt upgrade
    - name: Check Docker Version
      run: docker --version
    - name: Make some space 
      run: rm -rf /usr/share/dotnet
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
          python-version: '3.6'
    - name: Remove some folders
      run: |
        rm -rf navitia-docker-compose
        rm -rf artemis_data
        rm -rf artemis_references
    - name: Pull Navitia-docker-compose
      env:
        ARTEMIS_GITHUB_TOKEN: ${{ secrets.ARTEMIS_GITHUB_TOKEN }}
      run: |
        git clone https://$ARTEMIS_GITHUB_TOKEN@github.com/CanalTP/navitia-docker-compose.git --branch master ./navitia-docker-compose
        git clone https://$ARTEMIS_GITHUB_TOKEN@github.com/CanalTP/artemis_data.git --branch master ./artemis_data
        git clone https://$ARTEMIS_GITHUB_TOKEN@github.com/pbench/artemis_references.git --branch artemis_ng ./artemis_references
    - name: Build docker image
      env:
        ARTEMIS_GITHUB_TOKEN: ${{ secrets.ARTEMIS_GITHUB_TOKEN }}
      run: cd navitia-docker-compose/builder_from_package && ./build.sh -o $ARTEMIS_GITHUB_TOKEN -t local -e push -f CanalTP -b dev
    - name: Pull remaining images
      run: make pull_available TAG=local
    - name: Start all dockers 
      run: make start TAG=local
    - name: Run Artemis Test
      env:
        PYTEST: 'itl_test.py'
      run: make test || exit 0
    - name: Make Artemis Test
      run: make logs TAG=local > logs || exit 0
    - name: Archive Artemis artifacts
      uses: actions/upload-artifact@v2
      with:
        name: logs-and-ref
        path: |
            output/**/*
            junit/*.xml
            logs
